services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.9.0
    container_name: airflow-init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: bash -c "airflow db init"

  airflow:
    image: apache/airflow:2.9.0
    container_name: airflow
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: bash -c "airflow db upgrade && airflow webserver & airflow scheduler"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags   # ✅ Mount local dags folder inside container


    ngrok:
      image: ngrok/ngrok:latest   # official updated image
      container_name: ngrok
      depends_on:
        - airflow
      environment:
        - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      command: http airflow:8080

